import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { AuthProvider } from "@/context";
import NavWrapper from "./Components/NavWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
      
        <EdgeStoreProvider>  <NavWrapper/>{children}</EdgeStoreProvider> 
        </AuthProvider>

      
        </body>
    </html>
  );
}
